version: "3.8"
services:
  react-tutorial:
    container_name: react-tutorial
    hostname: react-tutorial
    restart: always
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "cd app && PORT=3000 npm start"
    expose:
      - 3000
    volumes:
      - ./src:/src
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.django.entrypoints=web
      - traefik.http.routers.django.rule=Host(`react.localhost`)

networks:
  web:
    name: docker-mgr_web
    external: true